// SVG-based DualSense renderer with 25 clickable hit zones.
//
// Geometry is traced from a user-provided line drawing — see
// scripts/trace_all.py + scripts/trace_share_options.py. The frozen
// output lives in controller_geom.generated.js, regenerated by running
// scripts/gen_controller_constants.py.
//
// The SVG uses a 240×130 viewBox. Coordinates place:
//   triggers (L2/R2) at the very top,
//   shoulders (L1/R1) just below them on the body's top edge,
//   D-pad at top-left of body, face buttons diamond at top-right,
//   touchpad centred above the body,
//   L-stick and R-stick wells in the lower half.
//   Virtual stick directions are spokes around each stick well (the
//   image's outer-ring decoration, rotated 45° so each spoke aligns to
//   one cardinal direction).
//
// Public API consumed by mappings.js (Task 20):
//   render(parent, bindings)       — mount the SVG inside `parent`, sized by CSS
//   flashPress(svg, id)            — yellow live-press highlight + ring animation
//   clearPress(svg, id)            — remove the live-press visuals
//   selectButton(svg, id)          — show the bind-popup-selection ring
//   clearSelection(svg)            — remove the selection ring
//
// `bindings` is an object keyed by stringified id:
//   { "0": { kind: "key"|"macro"|"unbound", value? }, ... }
//
// Click events bubble up from the hit zone. Each hit zone has `data-id="<n>"`;
// mappings.js listens for clicks on the SVG and reads
//   target.closest('[data-id]')

import {
  VIEWBOX,
  BODY_PATH,
  L1_RECT, R1_RECT, L2_RECT, R2_RECT,
  TOUCHPAD,
  TOUCHPAD_OUTER_PATH,
  LIGHT_BAR_INNER,
  LIGHT_BAR_INNER_PATH,
  DPAD_ARM_PATHS,
  FACE_BUTTONS,
  L_STICK, R_STICK,
  SPOKE_PATHS,
  PS_BUTTON,
  SHARE_PATH, OPTIONS_PATH,
} from './controller_geom.generated.js';

// Microphone slot — small rect centred between the sticks. Not visible
// in the source line drawing; kept at the same canonical position so
// the touchpad calibration UX (debug dot) has a visual reference.
const MIC_RECT = { x: 118, y: 80, w: 4, h: 1.5 };

// Gap between adjacent touchpad quadrants. Tune here if a designer
// wants a tighter or wider cross-line through the pad.
const TOUCHPAD_QUAD_GAP = 1.5;

// Per-button position fine-tune. Map id → { dx, dy }. Tuner generates
// this; production reads and applies as SVG translate. Empty by default.
export const BUTTON_OVERRIDES = new Map([
  // [13, { dx: -0.5, dy: 0 }],
]);

function applyButtonOverride(shape, id) {
  const o = BUTTON_OVERRIDES.get(id);
  if (!o) return;
  const dx = o.dx ?? 0;
  const dy = o.dy ?? 0;
  if (dx === 0 && dy === 0) return;
  shape.setAttribute('transform', `translate(${dx} ${dy})`);
}

// ─── Element descriptors ──────────────────────────────────────────────────────
//
// Returns array of element descriptors. Each descriptor with a numeric `id`
// produces ONE hit zone (<g data-id="N">). Sprite-only descriptors (no id)
// render decoration graphics only.

function elements() {
  return [
    // Triggers (L2/R2) — same rect shape as L1/R1, stacked above
    el(23, 'rect',    { ...L2_RECT },                       'L2'),
    el(24, 'rect',    { ...R2_RECT },                       'R2'),
    // Shoulders (L1/R1)
    el(9,  'rect',    { ...L1_RECT },                       'L1'),
    el(10, 'rect',    { ...R1_RECT },                       'R1'),

    // Share / Options — traced slanted-pill paths
    el(4,  'path',    { d: SHARE_PATH },                    'Share'),
    el(6,  'path',    { d: OPTIONS_PATH },                  'Options'),

    // Touchpad — 4 quadrant hit zones with a centre-cross gap
    ...touchpadQuadElements(),

    // PS logo button — between sticks
    el(5,  'circle',  { ...PS_BUTTON },                     'PS'),

    // D-pad — 4 traced pentagon paths
    el(11, 'path',    { d: DPAD_ARM_PATHS.up    },          'D-up'),
    el(12, 'path',    { d: DPAD_ARM_PATHS.down  },          'D-down'),
    el(13, 'path',    { d: DPAD_ARM_PATHS.left  },          'D-left'),
    el(14, 'path',    { d: DPAD_ARM_PATHS.right },          'D-right'),

    // Face buttons (right diamond) — traced positions + radius
    el(3,  'circle',  { ...FACE_BUTTONS.triangle },         'Triangle'),
    el(1,  'circle',  { ...FACE_BUTTONS.circle   },         'Circle'),
    el(0,  'circle',  { ...FACE_BUTTONS.cross    },         'Cross'),
    el(2,  'circle',  { ...FACE_BUTTONS.square   },         'Square'),

    // L stick well sprite (no hit zone)
    { sprite: 'stick_well', side: 'L', c: L_STICK },

    // L stick virtual wedges (ids 15–18) — traced spoke paths,
    // rotated 45° so they align to cardinal directions
    el(15, 'path',    { d: SPOKE_PATHS.left.up    },        'L-up'),
    el(16, 'path',    { d: SPOKE_PATHS.left.down  },        'L-down'),
    el(17, 'path',    { d: SPOKE_PATHS.left.left  },        'L-left'),
    el(18, 'path',    { d: SPOKE_PATHS.left.right },        'L-right'),

    // L3 (depressed L stick) — on top of wedges
    el(7,  'circle',  { cx: L_STICK.cx, cy: L_STICK.cy, r: 5 }, 'L3'),

    // R stick well sprite
    { sprite: 'stick_well', side: 'R', c: R_STICK },

    // R stick virtual wedges (ids 19–22)
    el(19, 'path',    { d: SPOKE_PATHS.right.up    },       'R-up'),
    el(20, 'path',    { d: SPOKE_PATHS.right.down  },       'R-down'),
    el(21, 'path',    { d: SPOKE_PATHS.right.left  },       'R-left'),
    el(22, 'path',    { d: SPOKE_PATHS.right.right },       'R-right'),

    // R3 — on top of R wedges
    el(8,  'circle',  { cx: R_STICK.cx, cy: R_STICK.cy, r: 5 }, 'R3'),
  ];
}

function el(id, kind, geo, label) {
  return { id, kind, geo, label };
}

function touchpadQuadElements() {
  const g = TOUCHPAD_QUAD_GAP;
  const r = TOUCHPAD.rx;
  const cx = TOUCHPAD.x + TOUCHPAD.w / 2;
  const cy = TOUCHPAD.y + TOUCHPAD.h / 2;
  const w = TOUCHPAD.w / 2 - g / 2;
  const h = TOUCHPAD.h / 2 - g / 2;
  const leftX  = TOUCHPAD.x;
  const rightX = cx + g / 2;
  const topY   = TOUCHPAD.y;
  const botY   = cy + g / 2;
  // `corner` names which of the 4 corners is the outer rounded one;
  // the other three corners are sharp (inner edges meeting the gap).
  return [
    el(25, 'touchpad_quad', { x: leftX,  y: topY, w, h, r, corner: 'tl' }, 'TP-TL'),
    el(26, 'touchpad_quad', { x: rightX, y: topY, w, h, r, corner: 'tr' }, 'TP-TR'),
    el(27, 'touchpad_quad', { x: leftX,  y: botY, w, h, r, corner: 'bl' }, 'TP-BL'),
    el(28, 'touchpad_quad', { x: rightX, y: botY, w, h, r, corner: 'br' }, 'TP-BR'),
  ];
}

// ─── Binding → CSS class ──────────────────────────────────────────────────────

function kindClass(kind) {
  switch (kind) {
    case 'key':     return 'binding-key';
    case 'macro':   return 'binding-macro';
    case 'mouse':   return 'binding-mouse';
    case 'unbound': return 'binding-unbound';
    default:        return 'binding-unbound';
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Mount the controller SVG inside `parent`. Returns the <svg> element.
 *
 * @param {Element} parent   - Container element (its innerHTML will be cleared).
 * @param {Object}  bindings - Map of id (string) → { kind, value? }.
 * @returns {SVGElement}
 */
export function render(parent, bindings) {
  const ns = 'http://www.w3.org/2000/svg';
  parent.innerHTML = '';

  const svg = document.createElementNS(ns, 'svg');
  svg.setAttribute('viewBox', VIEWBOX);
  svg.setAttribute('xmlns', ns);
  svg.classList.add('controller');

  // L2/R2 caps drawn first so the body silhouette overlaps their
  // lower edge for the stacked-pill look.
  for (const r of [L2_RECT, R2_RECT]) {
    const cap = mkRect(ns, r.x, r.y, r.w, r.h, 'body');
    cap.setAttribute('rx', String(r.rx));
    svg.appendChild(cap);
  }

  // Body silhouette
  const body = document.createElementNS(ns, 'path');
  body.setAttribute('d', BODY_PATH);
  body.classList.add('body');
  svg.appendChild(body);

  // L1/R1 caps drawn on top of body so their lower edge sits inside
  // the body outline.
  for (const r of [L1_RECT, R1_RECT]) {
    const cap = mkRect(ns, r.x, r.y, r.w, r.h, 'body');
    cap.setAttribute('rx', String(r.rx));
    svg.appendChild(cap);
  }

  // Touchpad outer — traced path (trapezoidal shape from the line
  // drawing, not the flat bbox the cursor-mapping code uses).
  const tp = document.createElementNS(ns, 'path');
  tp.setAttribute('d', TOUCHPAD_OUTER_PATH);
  tp.classList.add('touchpad');
  svg.appendChild(tp);

  // Light bar inner seam — traced inner-line of the touchpad surround.
  const bar = document.createElementNS(ns, 'path');
  bar.setAttribute('d', LIGHT_BAR_INNER_PATH);
  bar.classList.add('light-bar');
  bar.setAttribute('fill', 'none');
  svg.appendChild(bar);

  // Microphone slot decoration
  const mic = mkRect(ns, MIC_RECT.x, MIC_RECT.y, MIC_RECT.w, MIC_RECT.h, 'mic-slot');
  mic.setAttribute('rx', '0.6');
  svg.appendChild(mic);

  // Render each element descriptor
  for (const e of elements()) {
    if (e.sprite === 'stick_well') {
      const ring = mkCircle(ns, e.c.cx, e.c.cy, e.c.r, 'stick-ring');
      svg.appendChild(ring);
      continue;
    }

    // ── Hit zone ──
    const cls = kindClass((bindings[String(e.id)] || {}).kind);

    let shape;
    switch (e.kind) {
      case 'rect': {
        shape = mkRect(ns, e.geo.x, e.geo.y, e.geo.w, e.geo.h, `hit ${cls}`);
        if (e.geo.rx !== undefined) shape.setAttribute('rx', String(e.geo.rx));
        break;
      }
      case 'touchpad_quad': {
        // Each quadrant fills the touchpad rounded rect with ONE outer
        // corner curved (matching the pad's rx) and three inner corners
        // sharp, so the four quadrants together rebuild the rounded
        // touchpad outline with a cross-shaped gap in the middle.
        shape = mkTouchpadQuad(ns, e.geo, `hit ${cls}`);
        break;
      }
      case 'circle': {
        shape = mkCircle(ns, e.geo.cx, e.geo.cy, e.geo.r, `hit ${cls}`);
        break;
      }
      case 'path': {
        // D-pad arms, stick spokes, share/options — geometry comes
        // pre-baked from the line-art trace pipeline.
        shape = document.createElementNS(ns, 'path');
        shape.setAttribute('d', e.geo.d);
        shape.setAttribute('class', `hit ${cls}`);
        break;
      }
      default:
        continue;
    }

    shape.dataset.id    = String(e.id);
    shape.dataset.label = e.label;
    applyButtonOverride(shape, e.id);
    svg.appendChild(shape);
  }

  parent.appendChild(svg);
  return svg;
}

// ─── Live-press overlay ───────────────────────────────────────────────────────

// Keyed by stringified id → overlay <element>
const _flashes = new Map();

/**
 * Show a yellow press-ring animation over the hit zone for `id`.
 * Safe to call repeatedly — no-ops if already flashing.
 *
 * @param {SVGElement} svg
 * @param {number|string} id
 */
export function flashPress(svg, id) {
  const key = String(id);
  if (_flashes.has(key)) return;  // already active
  const target = svg.querySelector(`[data-id="${key}"]`);
  if (!target) return;

  const ring = _cloneAsOverlay(target, 'press-ring');
  svg.appendChild(ring);
  _flashes.set(key, ring);

  // Auto-remove after the animation finishes (250 ms + 20 ms buffer).
  setTimeout(() => {
    if (ring.parentNode) ring.remove();
    if (_flashes.get(key) === ring) _flashes.delete(key);
  }, 270);
}

/**
 * Remove the live-press ring for `id`, if present.
 *
 * @param {SVGElement} svg
 * @param {number|string} id
 */
export function clearPress(svg, id) {
  const key = String(id);
  const ring = _flashes.get(key);
  if (ring) {
    if (ring.parentNode) ring.remove();
    _flashes.delete(key);
  }
}

// ─── Touchpad debug dot ────────────────────────────────────────────────────────
//
// Renders a small dot on the touchpad SVG at the proportional position
// of the most recent click. Lets the user verify the raw coords being
// captured match where they actually touched — if they don't, the
// `touchpad_midpoint_x` / `touchpad_midpoint_y` settings can be tuned
// to match the user's physical pad coordinate range.

const TOUCHPAD_RAW_MAX_X = 1919;
const TOUCHPAD_RAW_MAX_Y = 1079;
let _debugDot = null;
let _debugDotTimer = null;

/**
 * Show a debug dot at the touchpad position corresponding to (raw_x,
 * raw_y). The dot fades by being removed after a short timeout.
 *
 * @param {SVGElement} svg
 * @param {number} raw_x  - 0..1919 (or whatever the pad reports)
 * @param {number} raw_y  - 0..1079
 */
export function showTouchpadDot(svg, raw_x, raw_y) {
  if (!svg) return;
  if (_debugDot && _debugDot.parentNode) _debugDot.remove();
  if (_debugDotTimer) clearTimeout(_debugDotTimer);
  const ns = 'http://www.w3.org/2000/svg';
  const dot = document.createElementNS(ns, 'circle');
  const cx = TOUCHPAD.x + (raw_x / TOUCHPAD_RAW_MAX_X) * TOUCHPAD.w;
  const cy = TOUCHPAD.y + (raw_y / TOUCHPAD_RAW_MAX_Y) * TOUCHPAD.h;
  dot.setAttribute('cx', String(cx));
  dot.setAttribute('cy', String(cy));
  dot.setAttribute('r',  '1.2');
  dot.setAttribute('class', 'touchpad-debug-dot');
  svg.appendChild(dot);
  _debugDot = dot;
  _debugDotTimer = setTimeout(() => {
    if (_debugDot === dot && dot.parentNode) dot.remove();
    if (_debugDot === dot) _debugDot = null;
    _debugDotTimer = null;
  }, 1200);
}

// ─── Touchpad hover preview ───────────────────────────────────────────────────
//
// Issue 3: continuous hover preview. While the finger is active, the engine
// emits 'touchpad-hover' per frame on quadrant change (dedupe-on-change),
// and on lift emits a sentinel `quadrant=255`. The frontend highlights the
// active quadrant and renders a persistent debug dot at the raw position.
// Distinct from `showTouchpadDot` (transient post-click) — this one updates
// live and persists while the finger is down.

let _hoverDot = null;

/**
 * Highlight quadrant `quadrantId` (25..=28) and move a persistent debug dot
 * to the proportional position of (rawX, rawY) inside the touchpad bbox.
 */
export function showTouchpadHover(svg, quadrantId, rawX, rawY) {
  if (!svg) return;
  // Highlight: add `hover` class to the matching quadrant, remove from others.
  for (const id of [25, 26, 27, 28]) {
    const el = svg.querySelector(`[data-id="${id}"]`);
    if (!el) continue;
    if (id === quadrantId) el.classList.add('hover');
    else                   el.classList.remove('hover');
  }
  // Debug dot: live-updated while finger is down.
  const ns = 'http://www.w3.org/2000/svg';
  if (!_hoverDot || !_hoverDot.parentNode) {
    _hoverDot = document.createElementNS(ns, 'circle');
    _hoverDot.setAttribute('r', '1.0');
    _hoverDot.setAttribute('class', 'touchpad-hover-dot');
    svg.appendChild(_hoverDot);
  }
  const cx = TOUCHPAD.x + (rawX / TOUCHPAD_RAW_MAX_X) * TOUCHPAD.w;
  const cy = TOUCHPAD.y + (rawY / TOUCHPAD_RAW_MAX_Y) * TOUCHPAD.h;
  _hoverDot.setAttribute('cx', String(cx));
  _hoverDot.setAttribute('cy', String(cy));
}

/**
 * Clear the hover highlight and remove the debug dot. Called on finger
 * lift (engine sentinel `quadrant=255`).
 */
export function clearTouchpadHover(svg) {
  if (!svg) return;
  for (const id of [25, 26, 27, 28]) {
    const el = svg.querySelector(`[data-id="${id}"]`);
    if (el) el.classList.remove('hover');
  }
  if (_hoverDot && _hoverDot.parentNode) {
    _hoverDot.remove();
  }
  _hoverDot = null;
}

// ─── Selection ring ───────────────────────────────────────────────────────────

let _selectionRing = null;

/**
 * Highlight `id` as the currently selected button (for the remap popup).
 * Replaces any previous selection.
 *
 * @param {SVGElement} svg
 * @param {number|string} id
 */
export function selectButton(svg, id) {
  clearSelection(svg);
  const target = svg.querySelector(`[data-id="${String(id)}"]`);
  if (!target) return;
  const ring = _cloneAsOverlay(target, 'selection-ring');
  svg.appendChild(ring);
  _selectionRing = ring;
}

/**
 * Remove the current selection ring, if any.
 *
 * @param {SVGElement} svg
 */
export function clearSelection(_svg) {
  if (_selectionRing) {
    if (_selectionRing.parentNode) _selectionRing.remove();
    _selectionRing = null;
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Clone a hit zone shape (geometry only) and assign the given overlay class.
 * Removes hit-zone-specific attributes so it doesn't capture clicks.
 *
 * @param {Element} target
 * @param {string}  cls     - CSS class ('press-ring' | 'selection-ring')
 * @returns {Element}
 */
function _cloneAsOverlay(target, cls) {
  const ring = target.cloneNode(false);
  ring.removeAttribute('class');
  ring.removeAttribute('data-id');
  ring.removeAttribute('data-label');
  ring.classList.add(cls);
  return ring;
}

// ─── SVG primitive factories ──────────────────────────────────────────────────

function mkRect(ns, x, y, w, h, cls) {
  const r = document.createElementNS(ns, 'rect');
  r.setAttribute('x',      String(x));
  r.setAttribute('y',      String(y));
  r.setAttribute('width',  String(w));
  r.setAttribute('height', String(h));
  r.setAttribute('class',  cls);
  return r;
}

function mkCircle(ns, cx, cy, r, cls) {
  const c = document.createElementNS(ns, 'circle');
  c.setAttribute('cx',    String(cx));
  c.setAttribute('cy',    String(cy));
  c.setAttribute('r',     String(r));
  c.setAttribute('class', cls);
  return c;
}

/**
 * Rectangle with exactly one rounded corner (the "outer" corner of a
 * touchpad quadrant). The other three corners are sharp so adjacent
 * quadrants share straight edges across the centre gap and the four
 * quadrants together rebuild the pad's rounded outer outline.
 *
 * `geo` shape:
 *   { x, y, w, h, r, corner: 'tl' | 'tr' | 'bl' | 'br' }
 */
function mkTouchpadQuad(ns, geo, cls) {
  const { x, y, w, h, r, corner } = geo;
  const path = (() => {
    const x1 = x + w, y1 = y + h;
    switch (corner) {
      case 'tl':
        return `M ${x} ${y + r} A ${r} ${r} 0 0 1 ${x + r} ${y} L ${x1} ${y} L ${x1} ${y1} L ${x} ${y1} Z`;
      case 'tr':
        return `M ${x} ${y} L ${x1 - r} ${y} A ${r} ${r} 0 0 1 ${x1} ${y + r} L ${x1} ${y1} L ${x} ${y1} Z`;
      case 'bl':
        return `M ${x} ${y} L ${x1} ${y} L ${x1} ${y1} L ${x + r} ${y1} A ${r} ${r} 0 0 1 ${x} ${y1 - r} Z`;
      case 'br':
      default:
        return `M ${x} ${y} L ${x1} ${y} L ${x1} ${y1 - r} A ${r} ${r} 0 0 1 ${x1 - r} ${y1} L ${x} ${y1} Z`;
    }
  })();
  const p = document.createElementNS(ns, 'path');
  p.setAttribute('d',     path);
  p.setAttribute('class', cls);
  return p;
}

