#!/usr/bin/env python3
"""Emit a JS constants module from dist/traced_features.json +
dist/share_options_geom.json so it can be pasted into rust/web/controller.js.

Produces rust/web/controller_geom.generated.js (auto-overwritten) plus
prints the same content to stdout for inspection.
"""
import json
from pathlib import Path

import re

REPO = Path(__file__).resolve().parent.parent
GEOM_PATH = REPO / "dist" / "traced_features.json"
SO_PATH = REPO / "dist" / "share_options_geom.json"
VIEWBOX_W = 240.0


def fmt(v, p=2):
    return f"{v:.{p}f}"


def mirror_path_x(d: str, axis_x: float = VIEWBOX_W / 2) -> str:
    """Reflect every X coordinate in an SVG path string across `axis_x`.

    Supports M/L/Q/Z (the only commands trace_all emits). All coords are
    absolute. Each command's args alternate (x, y). For Q the args are
    (cx, cy, x, y) — still alternating, so the same x-toggle logic works.
    """
    tokens = re.findall(r"[MLQZ]|-?\d+(?:\.\d+)?", d)
    out = []
    is_x = False  # toggle inside each command's number stream
    for t in tokens:
        if t in ("M", "L", "Q", "Z"):
            out.append(t)
            is_x = True
            continue
        if is_x:
            out.append(f"{(2 * axis_x - float(t)):.2f}")
        else:
            out.append(t)
        is_x = not is_x
    return " ".join(out)


def main():
    g = json.loads(GEOM_PATH.read_text())
    so = json.loads(SO_PATH.read_text())

    body_path = g["body_path"]
    l1, r1 = g["l1r1"]
    l2, r2 = g["l2r2_proposed"]
    tp_outer = g["touchpad_outer"]
    tp_inner = g["touchpad_inner"]
    dpad = g["dpad_arms"]
    fb = g["face_buttons"]
    sticks = g["sticks_outer"]
    spokes = g["stick_spokes_rotated"]
    ps = g["ps_button"]
    # Share is the canonical traced shape; Options is its mirror across
    # x=120 so the two pills are guaranteed identical in size and angle.
    # The raw Options trace was both smaller and shifted toward the body
    # edge — symmetrising fixes both at once.
    share = so["share"]["path"]
    options = mirror_path_x(share)

    L_STICK = sticks[0]
    R_STICK = sticks[1]

    # Partition spokes by anchor (left/right) and direction
    spokes_by = {"left": {}, "right": {}, "left_anchor": L_STICK,
                 "right_anchor": R_STICK}
    for s in spokes:
        spokes_by[s["anchor"]][s["dir"]] = s["path"]

    lines = []
    lines.append("// AUTO-GENERATED by scripts/gen_controller_constants.py")
    lines.append("// from dist/traced_features.json + dist/share_options_geom.json")
    lines.append("// Source PNGs:")
    lines.append("//   controller_frame.png (body, L1/R1, touchpad, D-pad, face, sticks, spokes, PS)")
    lines.append("//   RarGulhMQ0.png       (Share, Options)")
    lines.append("// All geometry in the 240×130 viewBox.")
    lines.append("")
    lines.append("export const VIEWBOX = '0 0 240 130';")
    lines.append("")
    lines.append("// Body silhouette — traced from user line drawing")
    lines.append(f"export const BODY_PATH =\n  '{body_path}';")
    lines.append("")
    lines.append("// L1 / R1 shoulder caps (traced)")
    lines.append(f"export const L1_RECT = {{ x: {l1['x']}, y: {l1['y']}, w: {l1['w']}, h: {l1['h']}, rx: 2 }};")
    lines.append(f"export const R1_RECT = {{ x: {r1['x']}, y: {r1['y']}, w: {r1['w']}, h: {r1['h']}, rx: 2 }};")
    lines.append("")
    lines.append("// L2 / R2 triggers — identical to L1/R1, stacked above with gap 1.5u")
    lines.append(f"export const L2_RECT = {{ x: {l2['x']}, y: {l2['y']}, w: {l2['w']}, h: {l2['h']}, rx: 2 }};")
    lines.append(f"export const R2_RECT = {{ x: {r2['x']}, y: {r2['y']}, w: {r2['w']}, h: {r2['h']}, rx: 2 }};")
    lines.append("")
    lines.append("// Touchpad — bbox is used for raw-coord → pixel mapping in")
    lines.append("// the cursor + hover code; the PATH is what gets rendered so")
    lines.append("// the trapezoidal light-bar shape from the line drawing is")
    lines.append("// preserved (bbox alone collapsed it to a flat rectangle).")
    lines.append(f"export const TOUCHPAD = {{ x: {tp_outer['x']}, y: {tp_outer['y']}, "
                 f"w: {tp_outer['w']}, h: {tp_outer['h']}, rx: 4 }};")
    lines.append(f"export const TOUCHPAD_OUTER_PATH =\n  '{tp_outer['path']}';")
    lines.append("")
    lines.append("// Light bar seam — traced inner-line of the touchpad surround")
    lines.append(f"export const LIGHT_BAR_INNER = {{ x: {tp_inner['x']}, y: {tp_inner['y']}, "
                 f"w: {tp_inner['w']}, h: {tp_inner['h']}, rx: 3 }};")
    lines.append(f"export const LIGHT_BAR_INNER_PATH =\n  '{tp_inner['path']}';")
    lines.append("")
    lines.append("// D-pad arms — 4 traced pentagon paths, one per direction")
    lines.append("export const DPAD_ARM_PATHS = {")
    for d in ("up", "down", "left", "right"):
        lines.append(f"  {d}: '{dpad[d]['path']}',")
    lines.append("};")
    lines.append("")
    lines.append("// Face buttons (traced circles)")
    lines.append("export const FACE_BUTTONS = {")
    for k in ("triangle", "circle", "cross", "square"):
        c = fb[k]
        lines.append(f"  {k}: {{ cx: {c['cx']}, cy: {c['cy']}, r: {c['r']} }},")
    lines.append("};")
    lines.append("")
    lines.append("// Stick wells (traced)")
    lines.append(f"export const L_STICK = {{ cx: {L_STICK['cx']}, cy: {L_STICK['cy']}, r: {L_STICK['r']} }};")
    lines.append(f"export const R_STICK = {{ cx: {R_STICK['cx']}, cy: {R_STICK['cy']}, r: {R_STICK['r']} }};")
    lines.append("")
    lines.append("// Stick outer-ring spokes — traced arc segments, rotated 45°")
    lines.append("// so each spoke aligns to one cardinal direction.")
    lines.append("export const SPOKE_PATHS = {")
    lines.append("  left: {")
    for d in ("up", "down", "left", "right"):
        lines.append(f"    {d}: '{spokes_by['left'][d]}',")
    lines.append("  },")
    lines.append("  right: {")
    for d in ("up", "down", "left", "right"):
        lines.append(f"    {d}: '{spokes_by['right'][d]}',")
    lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append(f"export const PS_BUTTON = {{ cx: {ps['cx']}, cy: {ps['cy']}, r: {ps['r']} }};")
    lines.append("")
    lines.append("// Share / Options — slanted-pill paths traced from secondary PNG")
    lines.append(f"export const SHARE_PATH = '{share}';")
    lines.append(f"export const OPTIONS_PATH = '{options}';")

    out = "\n".join(lines) + "\n"
    out_path = REPO / "rust" / "web" / "controller_geom.generated.js"
    out_path.write_text(out)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
